# Eat Safe, Love

## Notebook Set Up

In [1]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint
import pandas as pd

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [4]:
# review the collections in our database
print(db.list_collection_names())

['establishments']

In [5]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [6]:
establishments.find_one({})

{'_id': ObjectId('64b743aef210f6f10a3275e3'),
 'FHRSID': 1043695,
 'ChangesByServerID': 0,
 'LocalAuthorityBusinessID': 'PI/000073616',
 'BusinessName': 'The Pavilion',
 'BusinessType': 'Restaurant/Cafe/Canteen',
 'BusinessTypeID': 1,
 'AddressLine1': 'East Cliff Pavilion',
 'AddressLine2': 'Wear Bay Road',
 'AddressLine3': 'Folkestone',
 'AddressLine4': 'Kent',
 'PostCode': 'CT19 6BL',
 'Phone': '',
 'RatingValue': 5,
 'RatingKey': 'fhrs_5_en-gb',
 'RatingDate': '2018-04-04T00:00:00',
 'LocalAuthorityCode': '188',
 'LocalAuthorityName': 'Folkestone and Hythe',
 'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
 'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
 'scores': {'Hygiene': 5, 'Structural': 5, 'ConfidenceInManagement': 5},
 'SchemeType': 'FHRS',
 'geocode': {'longitude': 1.195625, 'latitude': 51.083812},
 'RightToReply': '',
 'Distance': 4591.765489457773,
 'NewRatingPending': False,
 'meta': {'dataSource': None,
  'extractDate': '0001-01-01T00:00:00',
  'itemCount': 0,
  'returncode': None,
  'totalCount': 0,
  'totalPages': 0,
  'pageSize': 0,
  'pageNumber': 0},
 'links': [{'rel': 'self',
   'href': 'https://api.ratings.food.gov.uk/establishments/1043695'}]}

In [7]:
# Find the establishments with a hygiene score of 20

query = {"scores.Hygiene" : 5 }

results = establishments.find(query)



# Use count_documents to display the number of documents in the result
count = establishments.count_documents((query))
print(f"Number of documents in the result: {count}\n")

# Display the first document in the results using pprint
pprint(results[0])

Number of documents in the result: 14002

{'AddressLine1': 'East Cliff Pavilion',
 'AddressLine2': 'Wear Bay Road',
 'AddressLine3': 'Folkestone',
 'AddressLine4': 'Kent',
 'BusinessName': 'The Pavilion',
 'BusinessType': 'Restaurant/Cafe/Canteen',
 'BusinessTypeID': 1,
 'ChangesByServerID': 0,
 'Distance': 4591.765489457773,
 'FHRSID': 1043695,
 'LocalAuthorityBusinessID': 'PI/000073616',
 'LocalAuthorityCode': '188',
 'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
 'LocalAuthorityName': 'Folkestone and Hythe',
 'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'CT19 6BL',
 'RatingDate': '2018-04-04T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('64b743aef210f6f10a3275e3'),
 'geocode': {'latitude': 51.083812, 'longitude': 1.195625},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/1043695',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}}

In [8]:
# Convert the result to a Pandas DataFrame

data = list(results)
hygiene_df = pd.json_normalize(data)

# Display the number of rows in the DataFrame
print("Number of rows in the dataframe: ", len(hygiene_df))


# Display the first 10 rows of the DataFrame
hygiene_df.head(10)

Number of rows in the dataframe:  14002

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,64b743aef210f6f10a3275e3,1043695,0,PI/000073616,The Pavilion,Restaurant/Cafe/Canteen,1,East Cliff Pavilion,Wear Bay Road,Folkestone,...,1.195625,51.083812,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,64b743aef210f6f10a3275e6,647177,0,PI/000041489,Wear Bay Bowls Club,Pub/bar/nightclub,7843,Wear Bay Road,Folkestone,Kent,...,1.196408,51.086058,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,64b743aef210f6f10a3275e9,289352,0,PI/000002460,The Ship,Pub/bar/nightclub,7843,23 The Stade,Folkestone,Kent,...,1.188537,51.080840,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,64b743aef210f6f10a3275ec,1068284,0,PI/000076532,The Tea Caddy,Mobile caterer,7846,Folkestone Harbour,Harbour Approach Road,Folkestone,...,1.185903,51.078352,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,64b743aef210f6f10a3275ed,1495230,0,PI/000078175,Lobster & Burger,Takeaway/sandwich shop,7844,Folkestone Harbour,Harbour Approach Road,Folkestone,...,1.185903,51.078352,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,64b743aef210f6f10a3275ef,805703,0,PI/000073221,That Burger - Harbour Arm,Takeaway/sandwich shop,7844,Folkestone Harbour,Harbour Approach Road,Folkestone,...,1.185903,51.078352,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,64b743aef210f6f10a3275f6,1043701,0,PI/000076360,Pick Up Pintxos,Takeaway/sandwich shop,7844,Folkestone Harbour,Harbour Approach Road,Folkestone,...,1.185903,51.078352,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,64b743aef210f6f10a3275f8,873838,0,PI/000074304,Hog & Hop - Harbour Arm,Takeaway/sandwich shop,7844,Folkestone Harbour,Harbour Approach Road,Folkestone,...,1.185903,51.078352,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,64b743aef210f6f10a3275fa,861820,0,PI/000074300,Waiting Room - Harbour Arm,Pub/bar/nightclub,7843,Folkestone Harbour,Harbour Approach Road,Folkestone,...,1.185903,51.078352,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,64b743aef210f6f10a3275fe,1138444,0,PI/000077128,Lucky Radish,Mobile caterer,7846,Folkestone Harbour,Harbour Approach Road,Folkestone,...,1.185903,51.078352,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [13]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {
        'LocalAuthorityName': {'$regex': "London"},
        "RatingValue" : {"$gte": 4},
        }

results = establishments.find(query)



# Use count_documents to display the number of documents in the result
count = establishments.count_documents((query))
print(f"Number of documents in the result: {count}\n")

# Display the first document in the results using pprint
pprint(results[0])

Number of documents in the result: 33

{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': 4,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('64b743aef210f6f10a32ab31'),
 'geocode': {'latitude': 51.369321, 'longitude': 0.508551},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [14]:
# Convert the result to a Pandas DataFrame
data = list(results)
london_df = pd.json_normalize(data)

# Display the number of rows in the DataFrame
print("Number of rows in the dataframe: ", len(london_df))


# Display the first 10 rows of the DataFrame
london_df.head(10)

Number of rows in the dataframe:  33

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,64b743aef210f6f10a32ab31,621707,0,PI/000025307,Charlie's,Other catering premises,7841,Oak Apple Farm Building 103 Sheernes Docks,Sheppy Kent,,...,0.508551,51.369321,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,64b743aef210f6f10a32ae58,1130836,0,PI/000034075,Mv City Cruises Erasmus,Other catering premises,7841,Cherry Garden Pier,Cherry Garden Street Rotherhithe,Charlton,...,0.249256,51.123623,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,64b743aef210f6f10a32b9a1,293783,0,PI/000002614,Benfleet Motor Yacht Club,Other catering premises,7841,Ferry Road,South Benfleet Essex,,...,0.561954,51.543831,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,64b743aff210f6f10a32c7a6,1315095,0,PI/000036464,Coombs Catering t/a The Lock and Key,Restaurant/Cafe/Canteen,1,Leslie Ford House,Tilbury,Charlton,...,0.346337,51.464066,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,64b743aff210f6f10a32c7ab,294474,0,PI/000014647,Tilbury Seafarers Centre,Restaurant/Cafe/Canteen,1,Tenants Row Tilbury Docks,Tilbury Essex,,...,0.346325,51.464078,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,64b743aff210f6f10a32ceae,294900,0,PI/000019066,Mv Valulla,Other catering premises,7841,Reeds River Cruises LtdKings ReachRiver Thames...,London,,...,0.287555,51.504071,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,64b743aff210f6f10a32efbc,293756,0,PI/000002538,Tereza Joanne,Other catering premises,7841,Funcraft UK Ltd King George V Dock Woolwich Ma...,London,,...,0.069286,51.501121,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,64b743aff210f6f10a32f37f,878523,0,PI/000029844,Brick Lane Brews,Restaurant/Cafe/Canteen,1,Air side London City Airport,London,,...,0.048006,51.503733,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,64b743aff210f6f10a32f39e,294606,0,PI/000016185,WH Smith,Retailers - other,4613,London City Airport,Silvertown London,,...,0.047966,51.504112,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,64b743aff210f6f10a32f3a0,295107,0,PI/000020749,City Bar & Grill,Restaurant/Cafe/Canteen,1,London City Airport (Airside),London,,...,0.047966,51.504112,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [ ]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
latitude = 51.49014200
longitude = 0.08384000

query = {
        ###,
        "RatingValue" : 5,
        }
sort = {'$sort': {"scores.Hygiene" : 1 }}


results = list(establishments.find(query).sort(sort).limit(5))
# Print the results

In [ ]:
# Convert result to Pandas DataFrame

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [16]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
match_query = {'$match': {"scores.Hygiene" : 5}}

# 2. Groups the matches by Local Authority
group_query = {'$group': {'_id': {"LocalAuthorityName": "$LocalAuthorityName"},
                           'count': { '$sum': 1 }
                           }}
                                  
# 3. Sorts the matches from highest to lowest
sort_values = {'$sort': { 'count': -1 }}

pipeline = [match_query, group_query, sort_values]

results = list(establishments.aggregate(pipeline))

# Print the number of documents in the result

print("Number of documents in result: ", len(results))

# Print the first 10 results
pprint(results[0:10])

Number of documents in result:  60
[{'_id': {'LocalAuthorityName': 'Redbridge'}, 'count': 964},
 {'_id': {'LocalAuthorityName': 'Wealden'}, 'count': 839},
 {'_id': {'LocalAuthorityName': 'Canterbury City'}, 'count': 750},
 {'_id': {'LocalAuthorityName': 'Rother'}, 'count': 664},
 {'_id': {'LocalAuthorityName': 'Newham'}, 'count': 662},
 {'_id': {'LocalAuthorityName': 'Havering'}, 'count': 621},
 {'_id': {'LocalAuthorityName': 'Colchester'}, 'count': 566},
 {'_id': {'LocalAuthorityName': 'Southend-On-Sea'}, 'count': 542},
 {'_id': {'LocalAuthorityName': 'Epping Forest'}, 'count': 539},
 {'_id': {'LocalAuthorityName': 'Bromley'}, 'count': 488}]

In [17]:
# Convert the result to a Pandas DataFrame
data = list(results)
low_h_score_df = pd.json_normalize(data)

# Display the number of rows in the DataFrame
print("Number of rows in the dataframe: ", len(low_h_score_df))


# Display the first 10 rows of the DataFrame
low_h_score_df.head(10)

Number of rows in the dataframe:  60

   count _id.LocalAuthorityName
0    964              Redbridge
1    839                Wealden
2    750        Canterbury City
3    664                 Rother
4    662                 Newham
5    621               Havering
6    566             Colchester
7    542        Southend-On-Sea
8    539          Epping Forest
9    488                Bromley